const mongoose = require('mongoose');

const Orders = new mongoose.Schema({
    shippingInfo:{
        address:{
            type:String,
            required:true,
        },
        city:{
            type:String,
            required:true
        },
        postalCode:{
            type:Number,
            required:true
        },
        phone:{
            type:Number,
            required:true
        },
        country:{
            type:String,
            required:true,
        },
        state:{
            type:String,
            required:true
        }
    },
    orderItems:[
        {
            image:{
                type:String,
                required:true,
            },
            name:{
                type:String,
                required:true,
            },
            qty:{
                type:Number,
                required:true,
            },
            price:{
                type:Number,
                required:true,
            },
            totalAmount:{
                type:Number,
                required:true
            },
            productReviewed:{
                type:String,
                required:true,
                default: 'No'
            },
            productId:{
                type:mongoose.Types.ObjectId,
                ref:"Products",
                required:true
            }
        }
    ],
    user:{
        type:mongoose.Types.ObjectId,
        ref:"User",
        required:true,
    },

    subTotal:{
        type:Number,
        required:true,
        default:0,
    },
    shippingCharges:{
        type:Number,
        required:true,
        default:0,
    },
    gstTax:{
        type:Number,
        required:true,
        default:0,
    },
    grossTotal:{
        type:Number,
        required:true,
        default:0,
    },
    paymentInfo:{
        id:{
            type:String,
            required:true
        },
        status:{
            type:String,
            required:true
        }
    },
    paidAt:{
        type:Date,
        required:true
    },
    orderStatus:{
        type:String,
        required:true,
        default:"processing"
    },
    deliveredAt:Date,
    createdAt:{
        type:Date,
        default:Date.now,
    }
})

module.exports = mongoose.model('Orders', Orders);